language: csharp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      mono: none
      dotnet: 1.0.3

env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1

script:
  - dotnet restore
  - dotnet build -c Release
  - dotnet test test/OpenTracing.Instrumentation.Tests/OpenTracing.Instrumentation.Tests.csproj -c Release --no-build
  - dotnet test test/OpenTracing.Tracer.BatchReporter.Tests/OpenTracing.Tracer.BatchReporter.Tests.csproj -c Release --no-build
